lines = []

lines.append("import json")
lines.append("import re")
lines.append("import time")
lines.append("from datetime import datetime")
lines.append("from playwright.sync_api import sync_playwright")
lines.append("")
lines.append("FUNDS = [")
lines.append("    {")
lines.append("        " + repr("id") + ": " + repr("LU2420245917") + ",")
lines.append("        " + repr("short") + ": " + repr("S&P 500 ESG") + ",")
lines.append("        " + repr("url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/historical?s=LU2420245917:SGD") + ",")
lines.append("        " + repr("summary_url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/summary?s=LU2420245917:SGD"))
lines.append("    },")
lines.append("    {")
lines.append("        " + repr("id") + ": " + repr("LU2420246139") + ",")
lines.append("        " + repr("short") + ": " + repr("MSCI World") + ",")
lines.append("        " + repr("url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/historical?s=LU2420246139:SGD") + ",")
lines.append("        " + repr("summary_url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/summary?s=LU2420246139:SGD"))
lines.append("    },")
lines.append("    {")
lines.append("        " + repr("id") + ": " + repr("LU2420246055") + ",")
lines.append("        " + repr("short") + ": " + repr("MSCI EM") + ",")
lines.append("        " + repr("url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/historical?s=LU2420246055:SGD") + ",")
lines.append("        " + repr("summary_url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/summary?s=LU2420246055:SGD"))
lines.append("    },")
lines.append("    {")
lines.append("        " + repr("id") + ": " + repr("LU2420246212") + ",")
lines.append("        " + repr("short") + ": " + repr("MSCI Europe") + ",")
lines.append("        " + repr("url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/historical?s=LU2420246212:SGD") + ",")
lines.append("        " + repr("summary_url") + ": " + repr("https://markets.ft.com/data/funds/tearsheet/summary?s=LU2420246212:SGD"))
lines.append("    }")
lines.append("]")
lines.append("")
lines.append("def scrape_fund(page, fund):")
lines.append("    print(" + repr("Scraping ") + " + fund[" + repr("short") + "] + " + repr("...") + ")")
lines.append("    page.goto(fund[" + repr("url") + "], wait_until=" + repr("networkidle") + ", timeout=60000)")
lines.append("    time.sleep(3)")
lines.append("    page.wait_for_selector(" + repr("table") + ", timeout=30000)")
lines.append("    rows = page.query_selector_all(" + repr("table tbody tr") + ")")
lines.append("    prices = []")
lines.append("    for row in rows:")
lines.append("        cols = row.query_selector_all(" + repr("td") + ")")
lines.append("        if len(cols) >= 2:")
lines.append("            date_text = cols[0].inner_text().strip()")
lines.append("            price_text = cols[1].inner_text().strip()")
lines.append("            price_clean = re.sub(r" + repr("[^\\d.]") + ", " + repr("") + ", price_text)")
lines.append("            try:")
lines.append("                price_val = float(price_clean)")
lines.append("                prices.append({" + repr("date") + ": date_text, " + repr("price") + ": price_val})")
lines.append("            except ValueError:")
lines.append("                continue")
lines.append("    return prices")
lines.append("")
lines.append("def calculate_changes(prices):")
lines.append("    result = []")
lines.append("    for i, entry in enumerate(prices):")
lines.append("        if i < len(prices) - 1:")
lines.append("            prev_price = prices[i + 1][" + repr("price") + "]")
lines.append("            curr_price = entry[" + repr("price") + "]")
lines.append("            pct_change = ((curr_price - prev_price) / prev_price) * 100")
lines.append("        else:")
lines.append("            pct_change = None")
lines.append("        result.append({" + repr("date") + ": entry[" + repr("date") + "], " + repr("price") + ": entry[" + repr("price") + "], " + repr("pct_change") + ": pct_change})")
lines.append("    return result")
lines.append("")
lines.append("def find_jan2_price(prices):")
lines.append("    for entry in reversed(prices):")
lines.append("        if (" + repr("Jan 02") + " in entry[" + repr("date") + "] or " + repr("Jan 2,") + " in entry[" + repr("date") + "]) and " + repr("2026") + " in entry[" + repr("date") + "]:")
lines.append("            return entry[" + repr("price") + "]")
lines.append("    if prices:")
lines.append("        return prices[-1][" + repr("price") + "]")
lines.append("    return None")
lines.append("")
lines.append("def main():")
lines.append("    all_data = {}")
lines.append("    with sync_playwright() as p:")
lines.append("        browser = p.chromium.launch(headless=True)")
lines.append("        context = browser.new_context(user_agent=" + repr("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36") + ")")
lines.append("        page = context.new_page()")
lines.append("        for fund in FUNDS:")
lines.append("            try:")
lines.append("                raw_prices = scrape_fund(page, fund)")
lines.append("                if not raw_prices:")
lines.append("                    print(" + repr("  No prices found for ") + " + fund[" + repr("short") + "])")
lines.append("                    continue")
lines.append("                priced = calculate_changes(raw_prices)[:5]")
lines.append("                jan2_price = find_jan2_price(raw_prices)")
lines.append("                latest_price = raw_prices[0][" + repr("price") + "] if raw_prices else None")
lines.append("                ytd_pct = ((latest_price - jan2_price) / jan2_price) * 100 if jan2_price and latest_price else None")
lines.append("                all_data[fund[" + repr("id") + "]] = {" + repr("short") + ": fund[" + repr("short") + "], " + repr("url") + ": fund[" + repr("summary_url") + "], " + repr("historical_url") + ": fund[" + repr("url") + "], " + repr("prices") + ": priced, " + repr("jan2_price") + ": jan2_price, " + repr("ytd_pct") + ": ytd_pct}")
lines.append("                print(" + repr("  Got ") + " + str(len(priced)) + " + repr(" days of data") + ")")
lines.append("            except Exception as e:")
lines.append("                print(" + repr("  Error scraping ") + " + fund[" + repr("short") + "] + " + repr(": ") + " + str(e))")
lines.append("        browser.close()")
lines.append("    output = {" + repr("last_updated") + ": datetime.utcnow().strftime(" + repr("%Y-%m-%d %H:%M UTC") + "), " + repr("funds") + ": all_data}")
lines.append("    with open(" + repr("data.json") + ", " + repr("w") + ") as f:")
lines.append("        json.dump(output, f, indent=2)")
lines.append("    print(" + repr("Done! Data saved to data.json") + ")")
lines.append("")
lines.append("if __name__ == " + repr("__main__") + ":")
lines.append("    main()")

with open("scraper.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("scraper.py written successfully")
